version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 10
    reviewers:
      - "agglayer/aggkit"
