issue-845-fix: true
with-expecter: true
resolve-type-alias: false
dir: "{{ .InterfaceDir }}/mocks"
outpkg: "mocks"
filename: "mock_{{ .InterfaceName | snakecase | lower }}.go"
mockname: "{{ .InterfaceName }}"
packages:
    github.com/agglayer/go_signer/signer:
      config:
        dir: "{{ .InterfaceDir }}/mocks"
        all: true