// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// TxSigner is an autogenerated mock type for the TxSigner type
type TxSigner struct {
	mock.Mock
}

type TxSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *TxSigner) EXPECT() *TxSigner_Expecter {
	return &TxSigner_Expecter{mock: &_m.Mock}
}

// SignTx provides a mock function with given fields: ctx, tx
func (_m *TxSigner) SignTx(ctx context.Context, tx *types.Transaction) (*types.Transaction, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for SignTx")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.Transaction) (*types.Transaction, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.Transaction) *types.Transaction); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.Transaction) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxSigner_SignTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignTx'
type TxSigner_SignTx_Call struct {
	*mock.Call
}

// SignTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *types.Transaction
func (_e *TxSigner_Expecter) SignTx(ctx interface{}, tx interface{}) *TxSigner_SignTx_Call {
	return &TxSigner_SignTx_Call{Call: _e.mock.On("SignTx", ctx, tx)}
}

func (_c *TxSigner_SignTx_Call) Run(run func(ctx context.Context, tx *types.Transaction)) *TxSigner_SignTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.Transaction))
	})
	return _c
}

func (_c *TxSigner_SignTx_Call) Return(_a0 *types.Transaction, _a1 error) *TxSigner_SignTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxSigner_SignTx_Call) RunAndReturn(run func(context.Context, *types.Transaction) (*types.Transaction, error)) *TxSigner_SignTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewTxSigner creates a new instance of TxSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxSigner {
	mock := &TxSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
