// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"
)

// HashSigner is an autogenerated mock type for the HashSigner type
type HashSigner struct {
	mock.Mock
}

type HashSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *HashSigner) EXPECT() *HashSigner_Expecter {
	return &HashSigner_Expecter{mock: &_m.Mock}
}

// SignHash provides a mock function with given fields: _a0, _a1
func (_m *HashSigner) SignHash(_a0 context.Context, _a1 common.Hash) ([]byte, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SignHash")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash) ([]byte, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash) []byte); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Hash) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HashSigner_SignHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignHash'
type HashSigner_SignHash_Call struct {
	*mock.Call
}

// SignHash is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 common.Hash
func (_e *HashSigner_Expecter) SignHash(_a0 interface{}, _a1 interface{}) *HashSigner_SignHash_Call {
	return &HashSigner_SignHash_Call{Call: _e.mock.On("SignHash", _a0, _a1)}
}

func (_c *HashSigner_SignHash_Call) Run(run func(_a0 context.Context, _a1 common.Hash)) *HashSigner_SignHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash))
	})
	return _c
}

func (_c *HashSigner_SignHash_Call) Return(_a0 []byte, _a1 error) *HashSigner_SignHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HashSigner_SignHash_Call) RunAndReturn(run func(context.Context, common.Hash) ([]byte, error)) *HashSigner_SignHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewHashSigner creates a new instance of HashSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHashSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *HashSigner {
	mock := &HashSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
