// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// RemoteSignerClienter is an autogenerated mock type for the RemoteSignerClienter type
type RemoteSignerClienter struct {
	mock.Mock
}

type RemoteSignerClienter_Expecter struct {
	mock *mock.Mock
}

func (_m *RemoteSignerClienter) EXPECT() *RemoteSignerClienter_Expecter {
	return &RemoteSignerClienter_Expecter{mock: &_m.Mock}
}

// EthAccounts provides a mock function with given fields: ctx
func (_m *RemoteSignerClienter) EthAccounts(ctx context.Context) ([]common.Address, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EthAccounts")
	}

	var r0 []common.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]common.Address, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []common.Address); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoteSignerClienter_EthAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EthAccounts'
type RemoteSignerClienter_EthAccounts_Call struct {
	*mock.Call
}

// EthAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RemoteSignerClienter_Expecter) EthAccounts(ctx interface{}) *RemoteSignerClienter_EthAccounts_Call {
	return &RemoteSignerClienter_EthAccounts_Call{Call: _e.mock.On("EthAccounts", ctx)}
}

func (_c *RemoteSignerClienter_EthAccounts_Call) Run(run func(ctx context.Context)) *RemoteSignerClienter_EthAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RemoteSignerClienter_EthAccounts_Call) Return(_a0 []common.Address, _a1 error) *RemoteSignerClienter_EthAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RemoteSignerClienter_EthAccounts_Call) RunAndReturn(run func(context.Context) ([]common.Address, error)) *RemoteSignerClienter_EthAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// SignHash provides a mock function with given fields: ctx, address, hashToSign
func (_m *RemoteSignerClienter) SignHash(ctx context.Context, address common.Address, hashToSign common.Hash) ([]byte, error) {
	ret := _m.Called(ctx, address, hashToSign)

	if len(ret) == 0 {
		panic("no return value specified for SignHash")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash) ([]byte, error)); ok {
		return rf(ctx, address, hashToSign)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Hash) []byte); ok {
		r0 = rf(ctx, address, hashToSign)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Hash) error); ok {
		r1 = rf(ctx, address, hashToSign)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoteSignerClienter_SignHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignHash'
type RemoteSignerClienter_SignHash_Call struct {
	*mock.Call
}

// SignHash is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
//   - hashToSign common.Hash
func (_e *RemoteSignerClienter_Expecter) SignHash(ctx interface{}, address interface{}, hashToSign interface{}) *RemoteSignerClienter_SignHash_Call {
	return &RemoteSignerClienter_SignHash_Call{Call: _e.mock.On("SignHash", ctx, address, hashToSign)}
}

func (_c *RemoteSignerClienter_SignHash_Call) Run(run func(ctx context.Context, address common.Address, hashToSign common.Hash)) *RemoteSignerClienter_SignHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Hash))
	})
	return _c
}

func (_c *RemoteSignerClienter_SignHash_Call) Return(_a0 []byte, _a1 error) *RemoteSignerClienter_SignHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RemoteSignerClienter_SignHash_Call) RunAndReturn(run func(context.Context, common.Address, common.Hash) ([]byte, error)) *RemoteSignerClienter_SignHash_Call {
	_c.Call.Return(run)
	return _c
}

// SignTx provides a mock function with given fields: ctx, from, tx
func (_m *RemoteSignerClienter) SignTx(ctx context.Context, from common.Address, tx *types.Transaction) (*types.Transaction, error) {
	ret := _m.Called(ctx, from, tx)

	if len(ret) == 0 {
		panic("no return value specified for SignTx")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *types.Transaction) (*types.Transaction, error)); ok {
		return rf(ctx, from, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *types.Transaction) *types.Transaction); ok {
		r0 = rf(ctx, from, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *types.Transaction) error); ok {
		r1 = rf(ctx, from, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoteSignerClienter_SignTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignTx'
type RemoteSignerClienter_SignTx_Call struct {
	*mock.Call
}

// SignTx is a helper method to define mock.On call
//   - ctx context.Context
//   - from common.Address
//   - tx *types.Transaction
func (_e *RemoteSignerClienter_Expecter) SignTx(ctx interface{}, from interface{}, tx interface{}) *RemoteSignerClienter_SignTx_Call {
	return &RemoteSignerClienter_SignTx_Call{Call: _e.mock.On("SignTx", ctx, from, tx)}
}

func (_c *RemoteSignerClienter_SignTx_Call) Run(run func(ctx context.Context, from common.Address, tx *types.Transaction)) *RemoteSignerClienter_SignTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*types.Transaction))
	})
	return _c
}

func (_c *RemoteSignerClienter_SignTx_Call) Return(_a0 *types.Transaction, _a1 error) *RemoteSignerClienter_SignTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RemoteSignerClienter_SignTx_Call) RunAndReturn(run func(context.Context, common.Address, *types.Transaction) (*types.Transaction, error)) *RemoteSignerClienter_SignTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewRemoteSignerClienter creates a new instance of RemoteSignerClienter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteSignerClienter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteSignerClienter {
	mock := &RemoteSignerClienter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
